CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL,
  "number_phone" varchar
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" text,
  "level" varchar,
  "teacher" varchar,
  "categories_id" int
);

CREATE TABLE "video_curses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "url" varchar NOT NULL,
  "course_id" int
);

ALTER TABLE "courses" ADD FOREIGN KEY ("id") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

ALTER TABLE "video_curses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");


-- Users

INSERT INTO "users" 
("first_name",
"last_name",
"email",
"password",
"number_phone") 
VALUES 
('Juan',
'Pérez',
'juanperez@gmail.com',
'123456',
'555-1234');
INSERT INTO "users" ("first_name",
 "last_name",
 "email",
 "password",
 "number_phone")
 VALUES 
('María',
 'García',
 'mariagarcia@gmail.com',
 'ytdkyt',
 '555-5678');

-- Categories

INSERT INTO "categories" 
("name")
VALUES
('Programación');
INSERT INTO "categories" 
("name") 
VALUES
('React');

-- Course

INSERT INTO "courses" 
("description",
 "level",
 "teacher",
 "categories_id")
 VALUES 
('Introducción a JavaScript'
,
 'beginner',
 'Juan Pérez',
 1);
INSERT INTO "courses" 
("description",
 "level",
 "teacher",
 "categories_id")
 values
('React Router DOM',
 'intermediate',
 'María García',
 2);

-- Video_courses

INSERT INTO "video_curses"
 ("title",
 "url",
 "course_id")
 values
 ('Video 1',
 'https://javascript.com/video1',
 1);
INSERT INTO "video_curses"
 ("title",
 "url",
 "course_id")
 values
 ('Video 2',
 'https://react.com/video2',
 2);